### PR TITLE
Update for 2023.2/2519561 (2023/11/14) release

### PR DESCRIPTION
**Pull request by chadlwilson**
See https://www.perforce.com/perforce/doc.current/user/relnotes.txt and https://cdist2.perforce.com/perforce/r23.2/bin.ntx64/SHA256SUMS

### CODE REVIEW

**Comment by chadlwilson** [comment]
Oh dear, seems the sha256 in the metadata from Perforce doesn't match the actual binary. Hmm.

**Comment by ripclawffb** [comment]
I think something is going on with the test environment. I created another PR because I had to update the package version. I pushed the new package and it passed Chocolatey's validation. I'll close this PR. Thanks for contributing.

**Comment by chadlwilson** [comment]
Ok, I think the issue was that P4 published the wrong sha256sums as when I downloaded the binary i got a different sum than they published (which is a little concerning)

**Comment by chadlwilson** [comment]
Seems they have fixed it now, so all good.

**Pull request closed without merging**
